refine variable forms

diff --git a/bin/bacp b/bin/bacp
--- a/bin/bacp
+++ b/bin/bacp
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+# Define default values
 PROTEOME=""
 INPUT=""
 REF=""
@@ -7,122 +8,103 @@ DB=""
 ALLELE=""
 OUTPUT=""
 THREADS=16
-BACNEO=$(echo $PATH | tr ':' '\n' | grep 'bacNeo' | uniq)
+BACNEO=$(echo "${PATH}" | tr ':' '\n' | grep 'bacNeo' | uniq)
 
 print_logo() {
-  echo -e "\e[36m"
-  echo '
+    echo -e "\e[36m"
+    echo '
                _                 _   _            
               | |               | \ | |           
               | |__   __ _  ___ |  \| | ___  ___   
               | `_ \ / _` |/ __|| . ` |/ _ \/ _ \  
               | |_) | (_| | (__ | |\  |  __/ (_) |
               |____/ \__,_|\___||_| \_|\___|\___/
-  '
-echo '
+    '
+    echo '
                _                    
               | |__   __ _  ___ _ __  
               | `_ \ / _` |/ __| `_ \ 
               | |_) | (_| | (__| |_) |
               |_.__/ \__,_|\___| .__/ 
                                |_|    
-'
-  echo -e "\e[0m"
+    '
+    echo -e "\e[0m"
 }
 
-usage() {                                 # Function: Print a help message.
-  echo "Usage: bacp [-p PROTEOME] [ -i INPUT ] [ -r REF ] [ -d DB ] [ -a ALLELE ] [ -o OUTPUT ] [ -t THREADS ]
-  -p Whether your datasets encompassing proteome data, 'y' for yes, 'n' for no. 
-  -i Input directory path:
-     when -p equals to 'y', please input MS data with '.d' format; 
-     when -p equals to 'n', please input the directory path of bacc output.
-  -r Directory path containing all reference proteome fasta files of your interested bacterial species. 
-     You could download them from UniProt (https://www.uniprot.org/), and put them into the path you input here.
-     It is highly recommended to make a clean directory, containing these fasta files only.
-  -d The directory path of your datasebases generated through bacNeo2 --download-db.
-  -a Directory path of bach results, including sample-name specific folders. 
-  -o Output directory path.
-  -t Number of threads (Default threads = 16).
-  Note: Before running bacp, be sure you have run bach to identify HLA alleles for each patient first.
-  If you have multiple sample files and want to run this command repeatedly, it is recommended to make independent directory for each sample.
-  If you input 'n' in parameter -p, -i and -r should be the same file." 1>&2 
-}
-exit_abnormal() {                         # Function: Exit with error.
-  usage
-  exit 1
+usage() {
+    echo "Usage: bacp [-p PROTEOME] [ -i INPUT ] [ -r REF ] [ -d DB ] [ -a ALLELE ] [ -o OUTPUT ] [ -t THREADS ]
+    -p Whether your datasets encompassing proteome data, 'y' for yes, 'n' for no. 
+    -i Input directory path:
+       when -p equals to 'y', please input MS data with '.d' format; 
+       when -p equals to 'n', please input the directory path of bacc output.
+    -r Directory path containing all reference proteome fasta files of your interested bacterial species. 
+       You could download them from UniProt (https://www.uniprot.org/), and put them into the path you input here.
+       It is highly recommended to make a clean directory, containing these fasta files only.
+    -d The directory path of your datasebases generated through bacNeo2 --download-db.
+    -a Directory path of bach results, including sample-name specific folders. 
+    -o Output directory path.
+    -t Number of threads (Default threads = 16).
+    Note: Before running bacp, be sure you have run bach to identify HLA alleles for each patient first.
+    If you have multiple sample files and want to run this command repeatedly, it is recommended to make independent directory for each sample.
+    If you input 'n' in parameter -p, -i and -r should be the same file." 1>&2 
 }
 
-while getopts ":p:i:r:d:a:o:t:" options; do # Loop: Get the next option;
-                                          # use silent error checking;
-                                          # options n and t take arguments.
-  case "${options}" in
-    p)
-        PROTEOME=${OPTARG}
-        ;;    
-    i)
-        INPUT=${OPTARG}
-        ;;
-    r)
-        REF=${OPTARG}
-        ;;
-    d)
-        DB=${OPTARG}
-        ;;
-    a)
-        ALLELE=${OPTARG}
-        ;;
-    o)
-        OUTPUT=${OPTARG}
-        ;;
-    t)
-        THREADS=${OPTARG}
-        ;;
-    :)                                    # If expected argument omitted:
-      echo "Error: -${OPTARG} requires an argument."
-      exit_abnormal                       # Exit abnormally.
-      ;;
-    *)                                    # If unknown (any other) option:
-      exit_abnormal                       # Exit abnormally.
-      ;;
-  esac
+exit_abnormal() {
+    usage
+    exit 1
+}
+
+while getopts ":p:i:r:d:a:o:t:" options; do
+    case "${options}" in
+        p) PROTEOME="${OPTARG}" ;;    
+        i) INPUT="${OPTARG}" ;;
+        r) REF="${OPTARG}" ;;
+        d) DB="${OPTARG}" ;;
+        a) ALLELE="${OPTARG}" ;;
+        o) OUTPUT="${OPTARG}" ;;
+        t) THREADS="${OPTARG}" ;;
+        :)
+            echo "Error: -${OPTARG} requires an argument."
+            exit_abnormal
+            ;;
+        *)
+            exit_abnormal
+            ;;
+    esac
 done
 
-# Function to process single sequence with sliding window
 process_sequence() {
-    local sequence=$1
+    local sequence="${1}"
     local window_size=10
     local step_size=3
     local seq_length=${#sequence}
-    
-    # Calculate number of windows
     local max_start=$((seq_length - window_size))
     
-    # Process each window position
     for ((i=0; i<=max_start; i+=step_size)); do
         echo "${sequence:$i:$window_size}"
     done
 }
 
 echo -e "\033[46;37m >> STEP 1: Extracting HLA alleles... \033[0m"
-mkdir -p ${OUTPUT}"/allele_summary"
-ls ${ALLELE} | while read SAMPLE
-do
-    find ${ALLELE}/${SAMPLE} -name "HLA-*.txt" | xargs awk '/HLA gene/ {split($0,a,": "); gene=a[2]} /Type [12]/ {split($3,b,":"); print gene b[1]":"b[2]}' > ${OUTPUT}"/allele_summary/"${SAMPLE}.txt
+mkdir -p "${OUTPUT}/allele_summary"
+
+ls "${ALLELE}" | while read -r SAMPLE; do
+    find "${ALLELE}/${SAMPLE}" -name "HLA-*.txt" | xargs awk '/HLA gene/ {split($0,a,": "); gene=a[2]} /Type [12]/ {split($3,b,":"); print gene b[1]":"b[2]}' > "${OUTPUT}/allele_summary/${SAMPLE}.txt"
 done
 
-if  [ ${PROTEOME} == "y" ]
-then
+if [ "${PROTEOME}" = "y" ]; then
     # Remove duplicates in reference fasta files
-    cat ${REF}/*.fasta > ${REF}/reference.fa
-    OUT_CDHIT=${REF}/reference_rmdup.fa
-    LOG_CDHIT=${OUTPUT}/cdhit.log
-    cd-hit -i ${REF}/reference.fa -o "$OUT_CDHIT" -c 0.9 -aS 0.9 -d 0 > "$LOG_CDHIT"
-        
-    mkdir ${OUTPUT}"/tmp"
-    ls ${INPUT} | grep ".d$" | sed 's/\(\.d\)//g' | awk '!a[$0]++' | while read SAMPLE
-    do
-        mkdir ${OUTPUT}/${SAMPLE}
-        fileXML=${OUTPUT}"/tmp/"${SAMPLE}".xml"
+    cat "${REF}"/*.fasta > "${REF}/reference.fa"
+    OUT_CDHIT="${REF}/reference_rmdup.fa"
+    LOG_CDHIT="${OUTPUT}/cdhit.log"
+    cd-hit -i "${REF}/reference.fa" -o "${OUT_CDHIT}" -c 0.9 -aS 0.9 -d 0 > "${LOG_CDHIT}"
+
+    mkdir -p "${OUTPUT}/tmp"
+    ls "${INPUT}" | grep "\.d$" | sed 's/\(\.d\)//g' | awk '!a[$0]++' | while read -r SAMPLE; do
+        mkdir -p "${OUTPUT}/${SAMPLE}"
+        fileXML="${OUTPUT}/tmp/${SAMPLE}.xml"
+
+        echo -e "\033[46;37m >> STEP 2: Running maxquant to identify peptides for sample ${SAMPLE}... \033[0m"
         echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
     <MaxQuantParams xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">
         <fastaFiles>
@@ -636,62 +618,69 @@ then
                 <InternalFragmentAas>KRH</InternalFragmentAas>
             </fragmentationParams>
         </fragmentationParamsArray>
-    </MaxQuantParams>" > ${fileXML}
-    echo -e "\033[46;37m >> STEP 2: Running maxquant to identify peptides for sample ${SAMPLE}... \033[0m"
-    maxquant ${fileXML}
-    rm ${fileXML}
+    </MaxQuantParams>" > "${fileXML}"
+        maxquant "${fileXML}"
+        rm "${fileXML}"
     done
-    rm -rf ${OUTPUT}"/tmp"
+    rm -rf "${OUTPUT}/tmp"
 
     echo -e "\033[46;37m >> STEP 3: Extracting peptide sequences... \033[0m"
-    Rscript ${BACNEO}"/pep_count.R" ${OUTPUT} ${BACNEO}
-    sed -i 's/\"//g' ${OUTPUT}"/sequences.txt"
+    Rscript "${BACNEO}/pep_count.R" "${OUTPUT}" "${BACNEO}"
+    sed -i 's/\"//g' "${OUTPUT}/sequences.txt"
 
     echo -e "\033[46;37m >> STEP 4: Predicting HLA-peptide affinities... \033[0m"
-    cat ${OUTPUT}"/hla_summary.txt" | while read type
-    do
-        ls ${ALLELE} | while read SAMPLE
-        do
-            netMHCpan -p ${OUTPUT}"/sequences.txt" -BA -xls -a ${type} -xlsfile ${OUTPUT}/${SAMPLE}'_'${type}.xls
+    while read -r type; do
+        ls "${ALLELE}" | while read -r SAMPLE; do
+            netMHCpan -p "${OUTPUT}/sequences.txt" -BA -xls -a "${type}" -xlsfile "${OUTPUT}/${SAMPLE}_${type}.xls"
         done
-    done
-elif [ ${PROTEOME} == "n" ]
-then
+    done < "${OUTPUT}/hla_summary.txt"
+
+elif [ "${PROTEOME}" = "n" ]; then
     echo -e "\033[46;37m >> STEP 2: Converting taxonomy reads into fasta files... \033[0m"  
-    mkdir -p ${OUTPUT}"/na_fastas"
-    ls ${INPUT} | while read SAMPLE
-    do
+    mkdir -p "${OUTPUT}/na_fastas"
+    
+    ls "${INPUT}" | while read -r SAMPLE; do
         echo "====================================================================="
         echo "Processing sample: ${SAMPLE}..."
-        python ${BACNEO}"/utils/bacp_taxon2fasta.py" -k ${INPUT}/${SAMPLE}/${SAMPLE}".KRAKEN" -s1 ${INPUT}/${SAMPLE}/${SAMPLE}"_unmap_R1.fq" -s2 ${INPUT}/${SAMPLE}/${SAMPLE}"_unmap_R2.fq" -o ${OUTPUT}"/na_fastas/"${SAMPLE}"_bacreads.fasta"
+        python "${BACNEO}/utils/bacp_taxon2fasta.py" \
+            -k "${INPUT}/${SAMPLE}/${SAMPLE}.KRAKEN" \
+            -s1 "${INPUT}/${SAMPLE}/${SAMPLE}_unmap_R1.fq" \
+            -s2 "${INPUT}/${SAMPLE}/${SAMPLE}_unmap_R2.fq" \
+            -o "${OUTPUT}/na_fastas/${SAMPLE}_bacreads.fasta"
     done
 
     echo -e "\033[46;37m >> STEP 3: Removing potential contaminants and predicting bacterial peptides... \033[0m"
-    mkdir -p ${OUTPUT}"/checkm2_predict/"
-    ls ${INPUT} | while read SAMPLE
-    do
+    mkdir -p "${OUTPUT}/checkm2_predict/"
+    
+    ls "${INPUT}" | while read -r SAMPLE; do
         echo "====================================================================="
         echo "Processing sample: ${SAMPLE}..."
-        mkdir -p ${OUTPUT}"/checkm2_predict/"${SAMPLE}
-        checkm2 predict --threads ${THREADS} --input ${OUTPUT}"/na_fastas/"${SAMPLE}"_bacreads.fasta" --output-directory ${OUTPUT}"/checkm2_predict/"${SAMPLE} --database_path ${DB}"/CheckM2_database/uniref100.KO.1.dmnd"
+        mkdir -p "${OUTPUT}/checkm2_predict/${SAMPLE}"
+        checkm2 predict --threads "${THREADS}" \
+            --input "${OUTPUT}/na_fastas/${SAMPLE}_bacreads.fasta" \
+            --output-directory "${OUTPUT}/checkm2_predict/${SAMPLE}" \
+            --database_path "${DB}/CheckM2_database/uniref100.KO.1.dmnd"
     done
 
     echo -e "\033[46;37m >> STEP 4: Predicting HLA-peptide affinities... \033[0m"
-    mkdir -p ${OUTPUT}"/aas"
-    mkdir -p ${OUTPUT}"/affinity"
-    ls ${INPUT} | while read SAMPLE
-    do
+    mkdir -p "${OUTPUT}/aas" "${OUTPUT}/affinity"
+    
+    ls "${INPUT}" | while read -r SAMPLE; do
         echo "====================================================================="
         echo "---------------------------------------------------------------------"
-        echo "Processing sample ${SAMPLE}: Removing duplicates in fasta files of bacteiral peptide..."
-        mkdir -p ${OUTPUT}"/affinity/"${SAMPLE}
-        OUT_CDHIT=${OUTPUT}"/aas/"${SAMPLE}"_bacpep_OUT_CDHIT.fa"
-        LOG_CDHIT=${OUTPUT}"/aas/"${SAMPLE}"_OUT_CDHIT.log"
-        cd-hit -i ${OUTPUT}"/checkm2_predict/"${SAMPLE}"/protein_files/"${SAMPLE}"_bacreads.faa" -o "$OUT_CDHIT" -c 0.9 -aS 0.9 -d 0 > "$LOG_CDHIT"
-        INPUT_PEP=${OUTPUT}"/aas/"${SAMPLE}"_bacpep.txt"
+        echo "Processing sample ${SAMPLE}: Removing duplicates in fasta files of bacterial peptide..."
+        
+        mkdir -p "${OUTPUT}/affinity/${SAMPLE}"
+        OUT_CDHIT="${OUTPUT}/aas/${SAMPLE}_bacpep_OUT_CDHIT.fa"
+        LOG_CDHIT="${OUTPUT}/aas/${SAMPLE}_OUT_CDHIT.log"
+        INPUT_PEP="${OUTPUT}/aas/${SAMPLE}_bacpep.txt"
+        
+        cd-hit -i "${OUTPUT}/checkm2_predict/${SAMPLE}/protein_files/${SAMPLE}_bacreads.faa" \
+            -o "${OUT_CDHIT}" -c 0.9 -aS 0.9 -d 0 > "${LOG_CDHIT}"
+
         # Remove sequences without start codon and ribosome binding sites
         awk '/^>/ {header=$0; getline seq; if (header !~ /rbs_motif=None/ && header !~ /start_type=Edge/) print seq}' \
-            "$OUT_CDHIT" > "$INPUT_PEP"
+            "${OUT_CDHIT}" > "${INPUT_PEP}"
         
         echo "---------------------------------------------------------------------"
         echo "Processing sample ${SAMPLE}: Window sliding..."
@@ -699,42 +688,39 @@ then
         TMP_WINDOW="${OUT_WINDOW}.temp"
 
         # Process each sequence in the input file
-        cat ${INPUT_PEP} | while read line
-        do
-            [ -z "$line" ] && continue
-            process_sequence "$line" >> "$TMP_WINDOW"
-        done
-        awk 'length($0) >= 5' "$TMP_WINDOW" > "$OUT_WINDOW"
-        rm "$INPUT_PEP"
+        while read -r line; do
+            [ -z "${line}" ] && continue
+            process_sequence "${line}" >> "${TMP_WINDOW}"
+        done < "${INPUT_PEP}"
+        
+        awk 'length($0) >= 5' "${TMP_WINDOW}" > "${OUT_WINDOW}"
+        rm "${INPUT_PEP}"
 
-        echo "Window sliding completed. Output saved to: $OUT_WINDOW"
+        echo "Window sliding completed. Output saved to: ${OUT_WINDOW}"
 
-        TMP_DIR=${OUTPUT}"/tmp_split_${SAMPLE}"
-        mkdir -p ${TMP_DIR}
+        TMP_DIR="${OUTPUT}/tmp_split_${SAMPLE}"
+        mkdir -p "${TMP_DIR}"
 
-        TOTAL_LINES=$(wc -l < ${OUT_WINDOW})
+        TOTAL_LINES=$(wc -l < "${OUT_WINDOW}")
         LINES_PER_THREAD=$(( (TOTAL_LINES + THREADS - 1) / THREADS ))
 
-        split -l ${LINES_PER_THREAD} ${OUT_WINDOW} ${TMP_DIR}/split_
+        split -l "${LINES_PER_THREAD}" "${OUT_WINDOW}" "${TMP_DIR}/split_"
         
-        cat ${OUTPUT}"/allele_summary/"${SAMPLE}".txt" | while read type
-        do
+        while read -r type; do
             echo "---------------------------------------------------------------------"
             echo "Predicting affinity for ${SAMPLE} - HLA allele ${type}..."
             
-            for split_file in ${TMP_DIR}/split_*
-            do
+            for split_file in "${TMP_DIR}"/split_*; do
                 (
-                    OUT_NETMHC=${OUTPUT}"/affinity/"${SAMPLE}/${SAMPLE}"_"${type}"_$(basename ${split_file}).xls"
-                    LOG_NETMHC=${OUTPUT}"/affinity/"${SAMPLE}/${SAMPLE}"_"${type}"_$(basename ${split_file}).log"
-                    netMHCpan -p ${split_file} -BA -xls -a ${type} -xlsfile ${OUT_NETMHC} > ${LOG_NETMHC}
+                    OUT_NETMHC="${OUTPUT}/affinity/${SAMPLE}/${SAMPLE}_${type}_$(basename "${split_file}").xls"
+                    LOG_NETMHC="${OUTPUT}/affinity/${SAMPLE}/${SAMPLE}_${type}_$(basename "${split_file}").log"
+                    netMHCpan -p "${split_file}" -BA -xls -a "${type}" -xlsfile "${OUT_NETMHC}" > "${LOG_NETMHC}"
                 ) &
                 
-                while [ $(jobs -r | wc -l) -ge ${THREADS} ]; do
+                while [ $(jobs -r | wc -l) -ge "${THREADS}" ]; do
                     sleep 1
                 done
             done
-            # Wait till all netMHCpan processes end
             wait
 
             echo "---------------------------------------------------------------------"
@@ -747,11 +733,9 @@ then
 
             if [ -n "${FIRST_RESULT}" ]; then
                 mkdir -p "$(dirname "${OUTPUT_FILE}")"
-                
                 head -n 1 "${FIRST_RESULT}" > "${OUTPUT_FILE}"
                 
-                for result in ${PATTERN}
-                do
+                for result in ${PATTERN}; do
                     if [ -f "${result}" ]; then
                         tail -n +2 "${result}" >> "${OUTPUT_FILE}"
                         rm -f "${result}"
@@ -760,14 +744,12 @@ then
             else
                 echo "Warning: No split files found matching pattern: ${PATTERN}"
             fi
-        done
-        rm -rf ${TMP_DIR}
+        done < "${OUTPUT}/allele_summary/${SAMPLE}.txt"
+        rm -rf "${TMP_DIR}"
     done
 else
     echo "Wrong parameter -p!"
 fi
 
-######################################################################################
-# Pending...
 echo -e "\033[46;37m Extracting sample-specific strong and weak binders... \033[0m"
-Rscript ${BACNEO}"/affinity_summary.R" ${OUTPUT}
+Rscript "${BACNEO}/affinity_summary.R" "${OUTPUT}"
